// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutDocumentDataSlicesSlice =
  | LeadershipGuidanceSlice
  | TeamMemberProfilesSlice
  | SectionHeaderSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>; /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type BlogArticleDocumentDataSlicesSlice =
  | TalentDevelopmentSlice
  | ImageComparisonSlice;

/**
 * Content for Blog documents
 */
interface BlogArticleDocumentData {
  /**
   * Titre field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image mise en avant field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *Blog*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  category: ContentRelationshipFieldWithData<
    [{ id: "blog_category"; fields: ["name", "description", "featured_image"] }]
  >;

  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogArticleDocumentDataSlicesSlice>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogArticleDocumentData>,
    "blog_article",
    Lang
  >;

type BlogArticlesDocumentDataSlicesSlice = SectionHeaderSlice;

/**
 * Content for Blog articles documents
 */
interface BlogArticlesDocumentData {
  /**
   * Slice Zone field in *Blog articles*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_articles.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogArticlesDocumentDataSlicesSlice>; /**
   * Meta Title field in *Blog articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_articles.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_articles.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog articles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_articles.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog articles document from Prismic
 *
 * - **API ID**: `blog_articles`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogArticlesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogArticlesDocumentData>,
    "blog_articles",
    Lang
  >;

/**
 * Content for Blog category documents
 */
interface BlogCategoryDocumentData {
  /**
   * Name field in *Blog category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Blog category document from Prismic
 *
 * - **API ID**: `blog_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogCategoryDocumentData>,
    "blog_category",
    Lang
  >;

type ContactDocumentDataSlicesSlice = SectionHeaderSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Contact email field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField;

  /**
   * Contact phone number field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact_phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_phone_number: prismic.KeyTextField;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>; /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Item in *Event → Modules*
 */
export interface EventDocumentDataModuleItem {
  /**
   * Title field in *Event → Modules*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.module[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Event → Modules*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.module[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Nom de l'événement field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Image mise en avant field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.image_mise_en_avant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_mise_en_avant: prismic.ImageField<never>;

  /**
   * Date de début field in *Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.start_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_date: prismic.DateField;

  /**
   * Date de fin field in *Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.end_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_date: prismic.DateField;

  /**
   * Description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Modules field in *Event*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: event.module[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  module: prismic.GroupField<Simplify<EventDocumentDataModuleItem>>;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

/**
 * Item in *Footer → Footer block*
 */
export interface FooterDocumentDataFooterBlockItem {
  /**
   * Title field in *Footer → Footer block*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_block[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *Footer → Footer block*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_block[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Footer block field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_block[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_block: prismic.GroupField<Simplify<FooterDocumentDataFooterBlockItem>>;

  /**
   * Copyright field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright: prismic.KeyTextField;

  /**
   * Legal link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  legal_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Global Navigation → Nav Item*
 */
export interface GlobalNavigationDocumentDataNavItemItem {
  /**
   * Display Text field in *Global Navigation → Nav Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global_navigation.nav_item[].display_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  display_text: prismic.KeyTextField;

  /**
   * url field in *Global Navigation → Nav Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global_navigation.nav_item[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Bold field in *Global Navigation → Nav Item*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: global_navigation.nav_item[].bold
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  bold: prismic.BooleanField;
}

/**
 * Content for Global Navigation documents
 */
interface GlobalNavigationDocumentData {
  /**
   * Nav Item field in *Global Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: global_navigation.nav_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  nav_item: prismic.GroupField<
    Simplify<GlobalNavigationDocumentDataNavItemItem>
  >;
}

/**
 * Global Navigation document from Prismic
 *
 * - **API ID**: `global_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalNavigationDocumentData>,
    "global_navigation",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | MissionValuesSlice
  | VisionStatementSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type LegalDocumentDataSlicesSlice = SectionHeaderSlice;

/**
 * Content for Legal documents
 */
interface LegalDocumentData {
  /**
   * content field in *Legal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Legal*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LegalDocumentDataSlicesSlice>; /**
   * Meta Title field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: legal.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legal.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Legal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Legal document from Prismic
 *
 * - **API ID**: `legal`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LegalDocumentData>, "legal", Lang>;

type ServicesDocumentDataSlicesSlice =
  | TestimonialSlice
  | CaseStudySlice
  | LeadershipGuidanceSlice
  | SectionHeaderSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice>; /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | BlogArticleDocument
  | BlogArticlesDocument
  | BlogCategoryDocument
  | ContactDocument
  | EventDocument
  | FooterDocument
  | GlobalNavigationDocument
  | HomeDocument
  | LegalDocument
  | ServicesDocument;

/**
 * Primary content in *CaseStudy → Default → Primary*
 */
export interface CaseStudySliceDefaultPrimary {
  /**
   * Title field in *CaseStudy → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *CaseStudy → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Body field in *CaseStudy → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *CaseStudy → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for CaseStudy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default case study variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudySliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CaseStudy → CaseStudyImageLeft → Primary*
 */
export interface CaseStudySliceCaseStudyImageLeftPrimary {
  /**
   * Title field in *CaseStudy → CaseStudyImageLeft → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.caseStudyImageLeft.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *CaseStudy → CaseStudyImageLeft → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.caseStudyImageLeft.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Body field in *CaseStudy → CaseStudyImageLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.caseStudyImageLeft.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *CaseStudy → CaseStudyImageLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.caseStudyImageLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * CaseStudyImageLeft variation for CaseStudy Slice
 *
 * - **API ID**: `caseStudyImageLeft`
 * - **Description**: Default case study variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudySliceCaseStudyImageLeft = prismic.SharedSliceVariation<
  "caseStudyImageLeft",
  Simplify<CaseStudySliceCaseStudyImageLeftPrimary>,
  never
>;

/**
 * Slice variation for *CaseStudy*
 */
type CaseStudySliceVariation =
  | CaseStudySliceDefault
  | CaseStudySliceCaseStudyImageLeft;

/**
 * CaseStudy Shared Slice
 *
 * - **API ID**: `case_study`
 * - **Description**: Case study section with title, subtitle, body content, and background image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudySlice = prismic.SharedSlice<
  "case_study",
  CaseStudySliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter hero title
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter hero subtitle
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Additional text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter footer descriptive text
   * - **API ID Path**: hero.default.primary.footerText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footerText: prismic.KeyTextField;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<"mobile">;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default hero variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero banner section with title, subtitle, background image, and descriptive footer text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageComparison → Default → Primary*
 */
export interface ImageComparisonSliceDefaultPrimary {
  /**
   * Left Image field in *ImageComparison → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_comparison.default.primary.leftImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  leftImage: prismic.ImageField<never>;

  /**
   * Right Image field in *ImageComparison → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_comparison.default.primary.rightImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  rightImage: prismic.ImageField<never>;
}

/**
 * Default variation for ImageComparison Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default image comparison variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageComparisonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageComparisonSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageComparison → Inversed → Primary*
 */
export interface ImageComparisonSliceInversedPrimary {
  /**
   * Left Image field in *ImageComparison → Inversed → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_comparison.inversed.primary.leftImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  leftImage: prismic.ImageField<never>;

  /**
   * Right Image field in *ImageComparison → Inversed → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_comparison.inversed.primary.rightImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  rightImage: prismic.ImageField<never>;
}

/**
 * Inversed variation for ImageComparison Slice
 *
 * - **API ID**: `inversed`
 * - **Description**: Default image comparison variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageComparisonSliceInversed = prismic.SharedSliceVariation<
  "inversed",
  Simplify<ImageComparisonSliceInversedPrimary>,
  never
>;

/**
 * Slice variation for *ImageComparison*
 */
type ImageComparisonSliceVariation =
  | ImageComparisonSliceDefault
  | ImageComparisonSliceInversed;

/**
 * ImageComparison Shared Slice
 *
 * - **API ID**: `image_comparison`
 * - **Description**: Two-column image comparison layout for visual side-by-side comparison
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageComparisonSlice = prismic.SharedSlice<
  "image_comparison",
  ImageComparisonSliceVariation
>;

/**
 * Primary content in *Service → Default → Primary*
 */
export interface LeadershipGuidanceSliceDefaultPrimary {
  /**
   * Main Heading field in *Service → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leadership_guidance.default.primary.mainHeading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  mainHeading: prismic.KeyTextField;

  /**
   * Subheading field in *Service → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leadership_guidance.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Description field in *Service → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leadership_guidance.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Service Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LeadershipGuidanceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LeadershipGuidanceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Service*
 */
type LeadershipGuidanceSliceVariation = LeadershipGuidanceSliceDefault;

/**
 * Service Shared Slice
 *
 * - **API ID**: `leadership_guidance`
 * - **Description**: Two-column layout with main heading on the left and descriptive content on the right
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LeadershipGuidanceSlice = prismic.SharedSlice<
  "leadership_guidance",
  LeadershipGuidanceSliceVariation
>;

/**
 * Primary content in *MissionsAndCta → Default → Primary*
 */
export interface MissionValuesSliceDefaultPrimary {
  /**
   * Title field in *MissionsAndCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_values.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * First Value Heading field in *MissionsAndCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Éclairer
   * - **API ID Path**: mission_values.default.primary.value_one_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value_one_heading: prismic.KeyTextField;

  /**
   * First Value Description field in *MissionsAndCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_values.default.primary.value_one_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value_one_description: prismic.KeyTextField;

  /**
   * Second Value Heading field in *MissionsAndCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Guider
   * - **API ID Path**: mission_values.default.primary.value_two_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value_two_heading: prismic.KeyTextField;

  /**
   * Second Value Description field in *MissionsAndCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_values.default.primary.value_two_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value_two_description: prismic.KeyTextField;

  /**
   * Third Value Heading field in *MissionsAndCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Accomplir
   * - **API ID Path**: mission_values.default.primary.value_three_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value_three_heading: prismic.KeyTextField;

  /**
   * Third Value Description field in *MissionsAndCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_values.default.primary.value_three_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value_three_description: prismic.KeyTextField;

  /**
   * Feature Image field in *MissionsAndCta → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_values.default.primary.feature_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  feature_image: prismic.ImageField<never>;

  /**
   * Tagline Heading field in *MissionsAndCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_values.default.primary.tagline_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline_heading: prismic.KeyTextField;

  /**
   * CTA Button Text field in *MissionsAndCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Découvrez nos services
   * - **API ID Path**: mission_values.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *MissionsAndCta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_values.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for MissionsAndCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MissionValuesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MissionValuesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MissionsAndCta*
 */
type MissionValuesSliceVariation = MissionValuesSliceDefault;

/**
 * MissionsAndCta Shared Slice
 *
 * - **API ID**: `mission_values`
 * - **Description**: Three-column mission values section with image and CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MissionValuesSlice = prismic.SharedSlice<
  "mission_values",
  MissionValuesSliceVariation
>;

/**
 * Primary content in *Header → Default → Primary*
 */
export interface SectionHeaderSliceDefaultPrimary {
  /**
   * Heading field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_header.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Background Image field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_header.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default section header variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type SectionHeaderSliceVariation = SectionHeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `section_header`
 * - **Description**: A section header with a heading and background image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionHeaderSlice = prismic.SharedSlice<
  "section_header",
  SectionHeaderSliceVariation
>;

/**
 * Primary content in *ArticleBlock → Default → Primary*
 */
export interface TalentDevelopmentSliceDefaultPrimary {
  /**
   * Title field in *ArticleBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section title
   * - **API ID Path**: talent_development.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *ArticleBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional subtitle or tagline
   * - **API ID Path**: talent_development.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Body field in *ArticleBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter rich text content
   * - **API ID Path**: talent_development.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for ArticleBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with title and body content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TalentDevelopmentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TalentDevelopmentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArticleBlock*
 */
type TalentDevelopmentSliceVariation = TalentDevelopmentSliceDefault;

/**
 * ArticleBlock Shared Slice
 *
 * - **API ID**: `talent_development`
 * - **Description**: Section for showcasing talent development and alignment content with title and rich text body
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TalentDevelopmentSlice = prismic.SharedSlice<
  "talent_development",
  TalentDevelopmentSliceVariation
>;

/**
 * Item in *TeamMemberProfiles → Default → Primary → Team Members*
 */
export interface TeamMemberProfilesSliceDefaultPrimaryMembersItem {
  /**
   * Profile Image field in *TeamMemberProfiles → Default → Primary → Team Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_profiles.default.primary.members[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *TeamMemberProfiles → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: John Doe
   * - **API ID Path**: team_member_profiles.default.primary.members[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Bio Description field in *TeamMemberProfiles → Default → Primary → Team Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Brief background...
   * - **API ID Path**: team_member_profiles.default.primary.members[].bio
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;
}

/**
 * Primary content in *TeamMemberProfiles → Default → Primary*
 */
export interface TeamMemberProfilesSliceDefaultPrimary {
  /**
   * Team Members field in *TeamMemberProfiles → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_profiles.default.primary.members[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  members: prismic.GroupField<
    Simplify<TeamMemberProfilesSliceDefaultPrimaryMembersItem>
  >;
}

/**
 * Default variation for TeamMemberProfiles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default team member profiles variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamMemberProfilesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamMemberProfilesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamMemberProfiles*
 */
type TeamMemberProfilesSliceVariation = TeamMemberProfilesSliceDefault;

/**
 * TeamMemberProfiles Shared Slice
 *
 * - **API ID**: `team_member_profiles`
 * - **Description**: Displays team member profiles with images, bios, and experience details
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamMemberProfilesSlice = prismic.SharedSlice<
  "team_member_profiles",
  TeamMemberProfilesSliceVariation
>;

/**
 * Primary content in *QuoteAndButton → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Author field in *QuoteAndButton → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Author name
   * - **API ID Path**: testimonial.default.primary.author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Quote field in *QuoteAndButton → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the testimonial quote
   * - **API ID Path**: testimonial.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  quote: prismic.KeyTextField;

  /**
   * Call to Action field in *QuoteAndButton → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for QuoteAndButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default testimonial variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuoteAndButton*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * QuoteAndButton Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: A testimonial slice featuring a quote with author attribution and call-to-action button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

/**
 * Primary content in *TextAndImage → Default → Primary*
 */
export interface VisionStatementSliceDefaultPrimary {
  /**
   * Title field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_statement.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_statement.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background Image field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_statement.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for TextAndImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VisionStatementSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VisionStatementSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextAndImage*
 */
type VisionStatementSliceVariation = VisionStatementSliceDefault;

/**
 * TextAndImage Shared Slice
 *
 * - **API ID**: `vision_statement`
 * - **Description**: Vision statement section with title, description text, and background image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VisionStatementSlice = prismic.SharedSlice<
  "vision_statement",
  VisionStatementSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      BlogArticleDocument,
      BlogArticleDocumentData,
      BlogArticleDocumentDataSlicesSlice,
      BlogArticlesDocument,
      BlogArticlesDocumentData,
      BlogArticlesDocumentDataSlicesSlice,
      BlogCategoryDocument,
      BlogCategoryDocumentData,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      EventDocument,
      EventDocumentData,
      EventDocumentDataModuleItem,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataFooterBlockItem,
      GlobalNavigationDocument,
      GlobalNavigationDocumentData,
      GlobalNavigationDocumentDataNavItemItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LegalDocument,
      LegalDocumentData,
      LegalDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      AllDocumentTypes,
      CaseStudySlice,
      CaseStudySliceDefaultPrimary,
      CaseStudySliceCaseStudyImageLeftPrimary,
      CaseStudySliceVariation,
      CaseStudySliceDefault,
      CaseStudySliceCaseStudyImageLeft,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageComparisonSlice,
      ImageComparisonSliceDefaultPrimary,
      ImageComparisonSliceInversedPrimary,
      ImageComparisonSliceVariation,
      ImageComparisonSliceDefault,
      ImageComparisonSliceInversed,
      LeadershipGuidanceSlice,
      LeadershipGuidanceSliceDefaultPrimary,
      LeadershipGuidanceSliceVariation,
      LeadershipGuidanceSliceDefault,
      MissionValuesSlice,
      MissionValuesSliceDefaultPrimary,
      MissionValuesSliceVariation,
      MissionValuesSliceDefault,
      SectionHeaderSlice,
      SectionHeaderSliceDefaultPrimary,
      SectionHeaderSliceVariation,
      SectionHeaderSliceDefault,
      TalentDevelopmentSlice,
      TalentDevelopmentSliceDefaultPrimary,
      TalentDevelopmentSliceVariation,
      TalentDevelopmentSliceDefault,
      TeamMemberProfilesSlice,
      TeamMemberProfilesSliceDefaultPrimaryMembersItem,
      TeamMemberProfilesSliceDefaultPrimary,
      TeamMemberProfilesSliceVariation,
      TeamMemberProfilesSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
      VisionStatementSlice,
      VisionStatementSliceDefaultPrimary,
      VisionStatementSliceVariation,
      VisionStatementSliceDefault,
    };
  }
}
