// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  case_study: defineAsyncComponent(() => import("./CaseStudy/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  image_comparison: defineAsyncComponent(
    () => import("./ImageComparison/index.vue"),
  ),
  leadership_guidance: defineAsyncComponent(
    () => import("./Service/index.vue"),
  ),
  mission_values: defineAsyncComponent(
    () => import("./MissionsAndCta/index.vue"),
  ),
  section_header: defineAsyncComponent(() => import("./Header/index.vue")),
  talent_development: defineAsyncComponent(
    () => import("./ArticleBlock/index.vue"),
  ),
  team_member_profiles: defineAsyncComponent(
    () => import("./TeamMemberProfiles/index.vue"),
  ),
  testimonial: defineAsyncComponent(() => import("./QuoteAndButton/index.vue")),
  vision_statement: defineAsyncComponent(
    () => import("./TextAndImage/index.vue"),
  ),
});
